[package]
name = "chainx"
version = "0.1.0"
authors = ["Chainpool <https://www.chainx.org>"]

[dependencies]
jsonrpc-macros = { git="https://github.com/paritytech/jsonrpc.git" }
substrate-network = { git = "https://github.com/chainx-org/substrate" }
substrate-network-libp2p = { git = "https://github.com/chainx-org/substrate" }
substrate-runtime-primitives = { git = "https://github.com/chainx-org/substrate" }
substrate-primitives = { git = "https://github.com/chainx-org/substrate" }
substrate-client = { git = "https://github.com/chainx-org/substrate" }
substrate-client-db = { git = "https://github.com/chainx-org/substrate" }
substrate-keyring = { git = "https://github.com/chainx-org/substrate" }
substrate-state-db = { git = "https://github.com/chainx-org/substrate" }
substrate-state-machine = { git = "https://github.com/chainx-org/substrate" }
substrate-telemetry = { git = "https://github.com/chainx-org/substrate" }
substrate-codec = { git = "https://github.com/chainx-org/substrate", default_features = false }
substrate-bft = { git = "https://github.com/chainx-org/substrate", default_features = false }
substrate-rpc-servers = { git = "https://github.com/chainx-org/substrate" }
substrate-runtime-balances = { git = "https://github.com/chainx-org/substrate" }
jsonrpc-http-server = { git = "https://github.com/paritytech/jsonrpc" }
jsonrpc-ws-server = { git = "https://github.com/paritytech/jsonrpc" }
ed25519 = { git = "https://github.com/chainx-org/substrate" }
ctrlc = { version = "3.0", features = ["termination"] }
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
chainx-primitives = { path = "./primitives" }
chainx-consensus = { path = "./consensus" }
chainx-executor = { path = "./executor" }
chainx-runtime = { path = "./runtime" }
chainx-network = { path = "./network" }
chainx-pool = { path = "./pool" }
chainx-test = { path = "./test" }
chainx-rpc = { path = "./rpc" }
chainx-api = { path = "./api" }
env_logger = "0.5.13"
rhododendron = "0.3"
hex-literal = "0.1"
exit-future = "0.1"
futures = "0.1.17"
ansi_term = "0.10"
sysinfo = "0.5.7"
tokio = "0.1.7"
clap = "2.30.0"
slog = "^2"
log = "0.3"

[workspace]
members = [
    "primitives",
    "consensus",
    "executor",
    "runtime",
    "network",
    "pool",
    "rpc",
    "api",
    "test"
]
